title: Portfolio
author: Faakeer Mohamed
email: faakeermohamed@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my portfolio includes my details my projects and contact details.

# social links
twitter_username: https://github.com/faakeer # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
